rustup:
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

bun:
  curl -fsSL https://bun.sh/install | bash

ghcup:
  sudo dnf install -y gcc gcc-c++ gmp gmp-devel make ncurses ncurses-compat-libs xz perl
  curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
